In [18]:
import torch

x_train = torch.FloatTensor([[1, 2, 1, 1], [2, 1, 3, 2], [3, 1, 3, 4], [4, 1, 5, 5], [1, 7, 5, 5], [1,2,5,6], [1,6, 6, 6], [1, 7, 7, 7]])
y_train = torch.FloatTensor([[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0], [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]])



In [19]:
W = torch.randn(4, 3, requires_grad = True)
b = torch.randn(1, 3, requires_grad = True)
optimizer = torch.optim.Adam([W, b], lr = 0.1)

for epoch in range(3001):
  # softmax hypothsis
  hypo = torch.softmax(torch.mm(x_train, W) + b, dim = 1) # dim = 1 각 벡터(리스트)마다 연산
  cost = -(y_train * torch.log(hypo)).sum(dim = 1).mean() # cross entropy

  optimizer.zero_grad() # with torhc.no_grad() W.grad = 0, b.grad = 0
  cost.backward()
  optimizer.step()

  with torch.no_grad():
    if epoch % 300 == 0:
      print(f"epoch: {epoch}, cost: {cost.item()}")


epoch: 0, cost: 8.532617568969727
epoch: 300, cost: 0.19016045331954956
epoch: 600, cost: 0.09715739637613297
epoch: 900, cost: 0.0584617480635643
epoch: 1200, cost: 0.03868718072772026
epoch: 1500, cost: 0.027216758579015732
epoch: 1800, cost: 0.019984988495707512
epoch: 2100, cost: 0.015143690630793571
epoch: 2400, cost: 0.011752012185752392
epoch: 2700, cost: 0.009290091693401337
epoch: 3000, cost: 0.007451973855495453


In [20]:
W.requires_grad_(False)
b.requires_grad_(False)

x_test = torch.FloatTensor([[1, 11, 10, 9], [1, 3, 4, 3], [1, 1, 0, 1]])
h = (torch.mm(x_test, W) + b).softmax(dim = 1)
test_all = torch.softmax(h, dim = 1)
# argmax = 해당 수식이 최대가 되는 값을 찾음
print(test_all)
print(torch.argmax(test_all, dim = 1))




tensor([[0.5761, 0.2119, 0.2119],
        [0.2344, 0.4528, 0.3128],
        [0.2119, 0.2119, 0.5761]])
tensor([0, 1, 2])


In [21]:
import torch.nn.functional as F
import torch.nn as nn

y_train = torch.LongTensor([2, 2, 2, 1, 1, 1, 0, 0])
model = nn.Linear(4, 3) # shape 와 동일
W = torch.randn(4, 3, requires_grad = True)
b = torch.randn(1, 3, requires_grad = True)
optimizer = torch.optim.Adam(model.parameters(), lr = 0.1)

for epoch in range(3001):
  # softmax hypothsis
  h = model(x_train)
  cost = F.cross_entropy(h, y_train)
  optimizer.zero_grad() # with torhc.no_grad() W.grad = 0, b.grad = 0
  cost.backward()
  optimizer.step()

  with torch.no_grad():
    if epoch % 300 == 0:
      print(f"epoch: {epoch}, cost: {cost.item()}")



epoch: 0, cost: 2.663395881652832
epoch: 300, cost: 0.14020684361457825
epoch: 600, cost: 0.06037745624780655
epoch: 900, cost: 0.03343347832560539
epoch: 1200, cost: 0.02111174911260605
epoch: 1500, cost: 0.014447448775172234
epoch: 1800, cost: 0.010429644957184792
epoch: 2100, cost: 0.00781738106161356
epoch: 2400, cost: 0.0060229068621993065
epoch: 2700, cost: 0.004737867042422295
epoch: 3000, cost: 0.0037874681875109673


In [22]:
x_test = torch.FloatTensor([[1, 11, 10, 9], [1, 3, 4, 3], [1, 1, 0, 1]])
h = model(x_test)
print(torch.argmax(h, dim = 1))

tensor([0, 1, 2])


In [23]:
import numpy as np
from sklearn.linear_model import LogisticRegression

x_train = np.array([[1, 2, 1, 1], [2, 1, 3, 2], [3, 1, 3, 4], [4, 1, 5, 5], [1,7 ,5 ,5], [1,2, 5, 6], [1, 6, 6, 6], [1, 7, 7, 7]])
y_train = np.array([2, 2, 2, 1, 1, 1, 0, 0])

logistic = LogisticRegression()
logistic.fit(x_train, y_train)

pred = logistic.predict([[1, 11, 10, 9], [1, 3, 4, 3], [1, 1, 0, 1]])
print(pred)

[0 2 2]
